name = "accessmate"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[kv_namespaces]]
binding = "KV"
id = "061aa66f056c46ce85e357ceef852617"
preview_id = "1bc9f88b75fe40b2a5d08f7a7757a205"

[[browser]]
binding = "BROWSER"
